{% set name = "django-simple-deploy" %}
{% set version = "0.7.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bdb4c257d8149d3f3ca21cd6ef8189476be05197e92586e4a2b76c9d7316f774

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - wheel

  run:
    - django >=4.2
    - python >=3.8
    - toml >=0.10.2
    - requests >=2.28.0
    - pluggy >=1.5.0

test:
  imports:
    - simple_deploy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ehmatthes/django-simple-deploy
  summary: A management command that auto-configures for deployment.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
