{% set name = "django-simple-deploy" %}
{% set version = "0.9.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5166f2eb75645b6a2c80c36cbf103725610aaec62a9f515493c91981769f2c65

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - wheel

  run:
    - python >={{ python_min }}
    - django >=4.2
    - toml >=0.10.2
    - requests >=2.32.2
    - pluggy >=1.5.0

test:
  imports:
    - simple_deploy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ehmatthes/django-simple-deploy
  summary: A management command that auto-configures for deployment.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
