{% set name = "django-simple-deploy" %}
{% set version = "0.6.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 86f63eac4e7bf980945a2d7944b63856d69a95013dfd39a3af0f01e70c9165f2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - django >=4.2
    - python >=3.8
    - toml >=0.10.2
    - requests >=2.28.0

test:
  imports:
    - simple_deploy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ehmatthes/django-simple-deploy
  summary: A management command that auto-configures for deployment.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
