{% set name = "django-simple-deploy" %}
{% set version = "0.5.14" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-simple-deploy-{{ version }}.tar.gz
  sha256: 4bf79955c1367872115bd2aa0e1f60e7f6b42d72affdb807f9b0a2be6a14641f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - wheel
  run:
    - django >=3.0
    - python >=3.8
    - python-tzdata

test:
  imports:
    - simple_deploy
    - simple_deploy.management.commands.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ehmatthes/django-simple-deploy
  summary: A management command that auto-configures for deployment.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
