{% set name = "django-simple-deploy" %}
{% set version = "0.5.16" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-simple-deploy-{{ version }}.tar.gz
  sha256: d0f97a60e7a5b0a871a2e5d5e73162a41604c9d7498ce7fc180827993cef42e6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - wheel
  run:
    - django >=3.0
    - python >=3.8
    - python-tzdata
    - toml >=0.10.2

test:
  imports:
    - simple_deploy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ehmatthes/django-simple-deploy
  summary: A management command that auto-configures for deployment.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
